services:
  mysql-db:
    image: mysql:8.0.19
    container_name: bit-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password  # CRITICAL: This sets the password for 'root'
      MYSQL_DATABASE: bit_app_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:5.0.7
    container_name: bit-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: